import bcrypt from "bcryptjs";

const data = {
  users: [
    // {
    //   name: "emma",
    //   email: "admin.test@test.com",
    //   password: bcrypt.hashSync("12345"),
    //   isAdmin: true,
    // },
    // {
    //   name: "nuel",
    //   email: "test@test.com",
    //   password: bcrypt.hashSync("12345"),
    //   isAdmin: false,
    // },
    {
      firstname: "emma",
      lastName: "nuel",
      otherName: "nedu",
      email: "admin.test@test.com",
      phone: 8130927634,
      gender: "male",
      street: "22 sariyu olusesu",
      lga: "alimosho",
      city: "egbe",
      zipCode: "10001",
      lgaOfOrigin: "idemili south",
      nationality: "nigerian",
      stateOfOrigin: "anambra",
      role: "Buyer",
      maritalStatus: "single",
      password: bcrypt.hashSync("1234567890"),
      isAdmin: true,
    },
    {
      firstname: "nuelSBN",
      lastName: "igwe",
      otherName: "nedu",
      email: "echinedu007@gmail.com",
      phone: 8130927622,
      gender: "male",
      street: "22 sariyu olusesu",
      lga: "alimosho",
      city: "egbe",
      zipCode: "10001",
      lgaOfOrigin: "idemili south",
      nationality: "nigerian",
      stateOfOrigin: "anambra",
      role: "Buyer",
      maritalStatus: "single",
      password: bcrypt.hashSync("1234567890"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Check Short Sleeve Shirt",
      slug: "check-short-sleeve-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      brand: "Prada",
      price: 2000,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        "2KShirts.ng is a thrift store. All items are like new or gently used. All gently used products are drycleaned and of the best quality!",
    },
    {
      name: "Shortsleeve Shirts",
      slug: "shortsleeve-shirts",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      brand: "Adidas",
      price: 2000,
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description:
        "2KShirts.ng is a thrift store. All items are like new or gently used. All gently used products are drycleaned and of the best quality!",
    },
    {
      name: "V Neck Tshirt",
      slug: "v-neck-tshirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      brand: "Zara",
      rating: 3,
      price: 12700,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Mens Pyjamas Set",
      slug: "mens-pyjamas-set",
      category: "Pants",
      image: "/images/pants1.jpg",
      brand: "Gucci",
      price: 25700,
      rating: 4,
      numReviews: 10,
      countInStock: 20,
      description:
        "2Kshirts.ng is a thrift store. All items are like new or gently used. All gently used products are drycleaned and of the best quality!",
    },
    {
      name: "Camo Combat Trouser",
      slug: "camo-combat-trouser",
      category: "Pants",
      image: "/images/pants2.jpg",
      brand: "Nike",
      price: 2900,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular Trouser",
    },
    {
      name: "Combat Trouser",
      slug: "combat-trouser",
      category: "Pants",
      image: "/images/pants3.jpg",
      brand: "Versace",
      price: 27000,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "gabardine chino trousers",
    },
  ],
};

export default data;
